import type { Channel, MediaAsset, AutopilotTriggerType } from '@/hooks/useSquadpitch';
import type {
  CampaignTypeRecommendation,
  ChannelRecommendation,
  MediaPrioritization,
  ScheduleRecommendation,
} from './campaignIntelligence.types';
import {
  recommendChannels,
  prioritizeMedia,
  buildIntelligentSchedule,
} from './campaignIntelligence';
import { getAdapter } from './adapterRegistry';
import type { IndustryAdapter } from './industryAdapter';

// ── Types ────────────────────────────────────────────────────────────────

export type CampaignUrgency = 'immediate' | 'high' | 'normal' | 'low';

export type ContentAngleHint =
  | 'urgency'
  | 'promotional'
  | 'storytelling'
  | 'lifestyle'
  | 'authority'
  | 'social_proof';

export type StatusChangeAction = 'generate' | 'pause' | 'skip';

/**
 * Structured recommendation output for a single trigger event.
 * This is the primary return type of the mapping layer.
 */
export interface TriggerCampaignRecommendation {
  /** Recommended campaign type from the assistant taxonomy */
  campaignType: CampaignTypeRecommendation;
  /** Urgency — determines how quickly the user should act */
  urgency: CampaignUrgency;
  /** Content angle hints for generation (ordered by priority) */
  angleHints: ContentAngleHint[];
  /** Whether generation should auto-proceed to draft-prep without user clicking "Generate" */
  autoGenerateDraft: boolean;
  /** Human-readable summary of why this recommendation was made */
  rationale: string;
  /** For status_changed triggers: whether to generate, pause existing, or skip */
  statusAction: StatusChangeAction;
}

/**
 * Input for deduplication check.
 * Caller passes recent recommendations to avoid spamming duplicates.
 */
export interface DedupeContext {
  /** Existing recommendation IDs for this listing, with their trigger types and timestamps */
  recentForListing: Array<{
    id: string;
    triggerType: AutopilotTriggerType;
    createdAt: string;
    status: string;
  }>;
}

/**
 * Result of deduplication check.
 */
export interface DedupeResult {
  /** Whether this recommendation should proceed */
  shouldCreate: boolean;
  /** If suppressed, why */
  suppressReason: string | null;
  /** If an existing recommendation should be superseded instead of creating new */
  supersedesId: string | null;
}

// ── Deduplication window (ms) ────────────────────────────────────────────

const DEDUPE_WINDOW_MS = 24 * 60 * 60 * 1000; // 24 hours
const SAME_TRIGGER_COOLDOWN_MS = 7 * 24 * 60 * 60 * 1000; // 7 days for same trigger type

// ══════════════════════════════════════════════════════════════════════════
// Public API
// ══════════════════════════════════════════════════════════════════════════

/**
 * Maps a trigger type to the recommended campaign type.
 * Uses direct deterministic mapping for known triggers,
 * falls back to recommendCampaignType for ambiguous cases.
 */
export function mapTriggerToCampaignType(
  triggerType: AutopilotTriggerType,
  propertyData: Record<string, unknown>,
  adapter: IndustryAdapter = getAdapter('real_estate'),
): CampaignTypeRecommendation {
  return adapter.mapTriggerToCampaignType(triggerType, propertyData);
}

/**
 * Produces a full structured recommendation for a trigger event.
 * This is the primary entry point for the mapping layer.
 */
export function buildTriggerRecommendation(
  triggerType: AutopilotTriggerType,
  propertyData: Record<string, unknown>,
  adapter: IndustryAdapter = getAdapter('real_estate'),
): TriggerCampaignRecommendation {
  const campaignType = adapter.mapTriggerToCampaignType(triggerType, propertyData);
  const triggerConf = adapter.triggerConfig[triggerType];
  const urgency = triggerConf?.urgency ?? 'normal';
  const angleHints = triggerConf?.angleHints ?? ['promotional'];
  const statusAction = resolveStatusAction(triggerType, propertyData);

  // Auto-generate only when confidence is high and trigger is deterministic
  const autoGenerateDraft =
    (triggerConf?.autoGenerate ?? false) &&
    campaignType.confidence === 'high' &&
    statusAction === 'generate';

  const rationale = buildRationale(triggerType, campaignType, propertyData);

  return {
    campaignType,
    urgency,
    angleHints,
    autoGenerateDraft,
    rationale,
    statusAction,
  };
}

/**
 * Checks whether a new recommendation should be created given recent history.
 * Prevents spamming duplicate recommendations for the same listing/event.
 */
export function checkDedupe(
  triggerType: AutopilotTriggerType,
  listingDataItemId: string,
  context: DedupeContext,
): DedupeResult {
  const now = Date.now();

  // Filter to active (non-dismissed, non-expired) recommendations
  const active = context.recentForListing.filter(
    (r) => r.status === 'pending' || r.status === 'generating' || r.status === 'ready',
  );

  // Rule 1: If the exact same trigger type exists within the cooldown window, suppress
  const sameTrigger = active.find((r) => {
    if (r.triggerType !== triggerType) return false;
    const age = now - new Date(r.createdAt).getTime();
    return age < SAME_TRIGGER_COOLDOWN_MS;
  });

  if (sameTrigger) {
    return {
      shouldCreate: false,
      suppressReason: `A ${triggerType} recommendation already exists for this listing (created ${formatAge(now - new Date(sameTrigger.createdAt).getTime())})`,
      supersedesId: null,
    };
  }

  // Rule 2: If any recommendation for this listing was created in the dedupe window, supersede it
  // (e.g., price_drop supersedes an earlier general_promotion for the same listing)
  const recentAny = active.find((r) => {
    const age = now - new Date(r.createdAt).getTime();
    return age < DEDUPE_WINDOW_MS;
  });

  if (recentAny && shouldSupersede(triggerType, recentAny.triggerType)) {
    return {
      shouldCreate: true,
      suppressReason: null,
      supersedesId: recentAny.id,
    };
  }

  // Rule 3: If there's already a pending/ready rec in the dedupe window but we can't supersede, suppress
  if (recentAny && !shouldSupersede(triggerType, recentAny.triggerType)) {
    return {
      shouldCreate: false,
      suppressReason: `A ${recentAny.triggerType} recommendation already exists for this listing within 24h`,
      supersedesId: null,
    };
  }

  return { shouldCreate: true, suppressReason: null, supersedesId: null };
}

// ── Full Autopilot Campaign Context (for display) ────────────────────────

export interface AutopilotCampaignContext {
  campaignType: CampaignTypeRecommendation;
  channels: ChannelRecommendation;
  media: MediaPrioritization | null;
  schedule: ScheduleRecommendation;
  /** Structured recommendation metadata */
  recommendation: TriggerCampaignRecommendation;
  /** Preferences context string for generation prompts (injected by hook, not computed here) */
  preferencesContext?: string | null;
}

/**
 * Composes all intelligence functions into a full context for display.
 * Used by AutopilotCampaignCard to show *why* a campaign was recommended.
 */
export function buildAutopilotCampaignContext(
  input: {
    triggerType: AutopilotTriggerType;
    propertyData: Record<string, unknown>;
    connectedChannels: Channel[];
    assets?: MediaAsset[];
  },
  adapter: IndustryAdapter = getAdapter('real_estate'),
): AutopilotCampaignContext {
  const recommendation = buildTriggerRecommendation(input.triggerType, input.propertyData, adapter);
  const { campaignType } = recommendation;

  const channels = recommendChannels({
    campaignType: campaignType.recommended,
    connectedChannels: input.connectedChannels,
    hasMedia: (input.assets?.length ?? 0) > 0,
    propertyData: input.propertyData,
  }, adapter);

  const media = input.assets && input.assets.length > 0
    ? prioritizeMedia(input.assets, {
        campaignType: campaignType.recommended,
        slotCount: channels.recommended.length,
      }, adapter)
    : null;

  const schedule = buildIntelligentSchedule({
    campaignType: campaignType.recommended,
    channels: channels.recommended,
    propertyData: input.propertyData,
  }, adapter);

  return { campaignType, channels, media, schedule, recommendation };
}

// ══════════════════════════════════════════════════════════════════════════
// Internal helpers
// ══════════════════════════════════════════════════════════════════════════

/**
 * Resolves the action for status_changed triggers.
 * For non-status_changed triggers, always returns 'generate'.
 */
function resolveStatusAction(
  triggerType: AutopilotTriggerType,
  propertyData: Record<string, unknown>,
): StatusChangeAction {
  if (triggerType !== 'status_changed') return 'generate';

  const listingStatus = (propertyData.listingStatus as string | undefined)?.toLowerCase();

  // Terminal statuses — skip generation
  if (listingStatus === 'sold' || listingStatus === 'closed' || listingStatus === 'withdrawn' || listingStatus === 'expired' || listingStatus === 'cancelled') {
    return 'pause';
  }

  // Pending — skip generation
  if (listingStatus === 'pending' || listingStatus === 'under_contract') {
    return 'skip';
  }

  // Active/other — generate
  return 'generate';
}

/**
 * Determines whether a new trigger type should supersede an existing one.
 * More specific/urgent triggers supersede less specific ones.
 */
function shouldSupersede(
  newTrigger: AutopilotTriggerType,
  existingTrigger: AutopilotTriggerType,
): boolean {
  // Spinstr05 priority order:
  //   open_house > price_drop > new_listing > just_sold > new_review >
  //   stale_listing > seasonal > inactivity_gap > status_changed (legacy)
  const priority: Record<AutopilotTriggerType, number> = {
    open_house_added: 9,
    open_house_updated: 8,
    price_drop: 7,
    new_listing: 6,
    just_sold: 5,
    new_review: 4,
    stale_listing: 3,
    seasonal: 2,
    inactivity_gap: 1,
    status_changed: 0,
  };

  return (priority[newTrigger] ?? 0) > (priority[existingTrigger] ?? 0);
}

/**
 * Builds a human-readable rationale string.
 */
function buildRationale(
  triggerType: AutopilotTriggerType,
  campaignType: CampaignTypeRecommendation,
  propertyData: Record<string, unknown>,
): string {
  const price = propertyData.price as number | undefined;
  const previousPrice = propertyData.previousPrice as number | undefined;
  const title = (propertyData.title as string) || (propertyData.address as string) || 'this property';

  switch (triggerType) {
    case 'new_listing':
      return `New listing detected for ${title}. ${campaignType.reason}`;
    case 'price_drop': {
      const drop = previousPrice && price
        ? ` ($${((previousPrice - price) / 1000).toFixed(0)}k reduction)`
        : '';
      return `Price drop detected for ${title}${drop}. Urgency-driven campaigns perform 2-3x better in the first 48 hours.`;
    }
    case 'open_house_added':
      return `Open house scheduled for ${title}. A campaign driving attendance should launch 3-5 days before the event.`;
    case 'open_house_updated':
      return `Open house details updated for ${title}. A reminder campaign can recapture interest from earlier viewers.`;
    case 'status_changed': {
      const status = (propertyData.listingStatus as string) ?? 'unknown';
      return `Listing status changed to "${status}" for ${title}. ${campaignType.reason}`;
    }
    default:
      return campaignType.reason;
  }
}

function formatAge(ms: number): string {
  const hours = Math.floor(ms / (60 * 60 * 1000));
  if (hours < 1) return 'just now';
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  return `${days}d ago`;
}
