export default function SmsConsentPage() {
  return (
    <div className="min-h-screen bg-[#111318] text-white flex items-center justify-center p-6">
      <div className="max-w-xl w-full space-y-6">
        <h1 className="text-2xl font-bold">SMS — Temporarily unavailable</h1>

        <section className="space-y-3 text-sm text-gray-300 leading-relaxed">
          <p>
            Squadpitch does not currently offer SMS notifications. SMS setup,
            consent controls, and sending are disabled.
          </p>

          <h2 className="text-lg font-semibold text-white pt-2">
            Current status
          </h2>
          <ul className="list-disc list-inside space-y-1">
            <li>Post failed to publish</li>
            <li>Channel connection expired</li>
          </ul>
          <p>
            These categories are retained for future reference only. No SMS is
            currently sent for account, marketing, or promotional messages.
          </p>

          <h2 className="text-lg font-semibold text-white pt-2">
            Opt-in status
          </h2>
          <p>
            There is currently no SMS opt-in or phone-number setup flow. Any
            future reactivation will require a new, explicit consent review.
          </p>

          <h2 className="text-lg font-semibold text-white pt-2">
            How to opt out
          </h2>
          <p>
            SMS is already disabled. For questions about historical consent or
            messages, contact us at{" "}
            <a
              href="mailto:support@squadpitch.com"
              className="text-green-400 hover:underline"
            >
              support@squadpitch.com
            </a>
            .
          </p>

          <h2 className="text-lg font-semibold text-white pt-2">
            Message frequency
          </h2>
          <p>Current message frequency is zero because SMS is unavailable.</p>

          <h2 className="text-lg font-semibold text-white pt-2">Rates</h2>
          <p>
            No SMS charges should be generated by Squadpitch while the feature
            is unavailable.
          </p>
        </section>

        <p className="text-xs text-gray-500 pt-4 border-t border-gray-800">
          Squadpitch &middot; Last updated August 2026
        </p>
      </div>
    </div>
  );
}
