'use client';

import { useMemo, useState } from 'react';
import { Search, Inbox, List, LayoutGrid, Zap, Home, Wand2 } from 'lucide-react';
import { cn } from '@/lib/utils';
import {
  useDrafts,
  type Draft,
  type DraftStatus,
  type Channel,
} from '@/hooks/useSquadpitch';
import { LoadingSpinner } from '@/components/common/LoadingSpinner';
import { StatusBanner } from '@/components/common/StatusBanner';
import { DraftQueueCard } from './DraftQueueCard';
import { AssetLibrary } from './AssetLibrary';

interface Props {
  clientId: string;
}

type Tab = 'ALL' | DraftStatus | 'MEDIA';
type SourceFilter = 'all' | 'autopilot' | 'listing' | 'manual';
type ViewMode = 'list' | 'grid';

const TABS: Array<{ label: string; value: Tab }> = [
  { label: 'All Content', value: 'ALL' },
  { label: 'Drafts', value: 'DRAFT' },
  { label: 'Scheduled', value: 'SCHEDULED' },
  { label: 'Published', value: 'PUBLISHED' },
  { label: 'Failed', value: 'FAILED' },
  { label: 'Media', value: 'MEDIA' },
];

const SOURCE_FILTERS: Array<{
  label: string;
  value: SourceFilter;
  icon: React.ReactNode;
}> = [
  { label: 'All sources', value: 'all', icon: null },
  { label: 'Autopilot', value: 'autopilot', icon: <Zap className="w-3 h-3" /> },
  { label: 'Listings', value: 'listing', icon: <Home className="w-3 h-3" /> },
  { label: 'Manual', value: 'manual', icon: <Wand2 className="w-3 h-3" /> },
];

const CHANNEL_FILTERS: Array<{
  label: string;
  value: Channel | 'ALL';
}> = [
  { label: 'All channels', value: 'ALL' },
  { label: 'Instagram', value: 'INSTAGRAM' },
  { label: 'TikTok', value: 'TIKTOK' },
  { label: 'X', value: 'X' },
  { label: 'LinkedIn', value: 'LINKEDIN' },
  { label: 'Facebook', value: 'FACEBOOK' },
  { label: 'YouTube', value: 'YOUTUBE' },
];

function matchesSource(draft: Draft, filter: SourceFilter): boolean {
  if (filter === 'all') return true;
  const sm = draft.sourceMeta;
  if (filter === 'autopilot') return Boolean(sm?.autopilot || sm?.autoGenerated);
  if (filter === 'listing') return sm?.source === 'listing';
  if (filter === 'manual') return !sm?.autopilot && !sm?.autoGenerated;
  return true;
}

export function ContentLibrary({ clientId }: Props) {
  const [tab, setTab] = useState<Tab>('ALL');
  const [channelFilter, setChannelFilter] = useState<Channel | 'ALL'>('ALL');
  const [sourceFilter, setSourceFilter] = useState<SourceFilter>('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [viewMode, setViewMode] = useState<ViewMode>('list');

  const { data: allDrafts, isLoading, error } = useDrafts({
    clientId,
    limit: 200,
  });

  // Filter by tab (status)
  const tabFiltered = useMemo(() => {
    if (!allDrafts) return undefined;
    if (tab === 'ALL' || tab === 'MEDIA') return allDrafts;
    return allDrafts.filter((d) => d.status === tab);
  }, [allDrafts, tab]);

  // Filter by channel
  const channelFiltered = useMemo(() => {
    if (!tabFiltered) return undefined;
    if (channelFilter === 'ALL') return tabFiltered;
    return tabFiltered.filter((d) => d.channel === channelFilter);
  }, [tabFiltered, channelFilter]);

  // Filter by source
  const sourceFiltered = useMemo(() => {
    if (!channelFiltered) return undefined;
    return channelFiltered.filter((d) => matchesSource(d, sourceFilter));
  }, [channelFiltered, sourceFilter]);

  // Filter by search
  const drafts = useMemo(() => {
    if (!sourceFiltered) return undefined;
    if (!searchQuery.trim()) return sourceFiltered;
    const q = searchQuery.toLowerCase();
    return sourceFiltered.filter(
      (d) =>
        d.body?.toLowerCase().includes(q) ||
        d.hooks?.some((h) => h.toLowerCase().includes(q)) ||
        d.cta?.toLowerCase().includes(q) ||
        d.hashtags?.some((h) => h.toLowerCase().includes(q)) ||
        d.sourceMeta?.listingTitle?.toLowerCase().includes(q)
    );
  }, [sourceFiltered, searchQuery]);

  // Tab counts
  const tabCounts = useMemo(() => {
    if (!allDrafts) return {};
    const counts: Record<string, number> = { ALL: allDrafts.length };
    for (const d of allDrafts) {
      counts[d.status] = (counts[d.status] ?? 0) + 1;
    }
    return counts;
  }, [allDrafts]);

  // Source counts (for badge numbers)
  const sourceCounts = useMemo(() => {
    if (!channelFiltered) return {};
    const counts: Record<string, number> = { all: channelFiltered.length };
    for (const d of channelFiltered) {
      if (d.sourceMeta?.autopilot || d.sourceMeta?.autoGenerated) counts.autopilot = (counts.autopilot ?? 0) + 1;
      if (d.sourceMeta?.source === 'listing') counts.listing = (counts.listing ?? 0) + 1;
      if (!d.sourceMeta?.autopilot && !d.sourceMeta?.autoGenerated) counts.manual = (counts.manual ?? 0) + 1;
    }
    return counts;
  }, [channelFiltered]);

  // Tab bar (shared between media and draft views)
  const tabBar = (
    <div className="flex gap-1 border-b border-white-10">
      {TABS.map((t) => {
        const count = tabCounts[t.value] ?? 0;
        return (
          <button
            key={t.value}
            onClick={() => setTab(t.value)}
            className={cn(
              'px-4 py-2.5 text-sm font-medium transition-colors border-b-2 -mb-px',
              tab === t.value
                ? 'text-accent-green-110 border-accent-green-110'
                : 'text-white-40 border-transparent hover:text-white-100'
            )}
          >
            {t.label}
            {t.value !== 'MEDIA' && count > 0 && (
              <span className="ml-1.5 text-white-30">({count})</span>
            )}
          </button>
        );
      })}
    </div>
  );

  if (tab === 'MEDIA') {
    return (
      <div className="space-y-5">
        <h1 className="text-xl font-bold text-white-100">Content Library</h1>
        {tabBar}
        <AssetLibrary clientId={clientId} />
      </div>
    );
  }

  return (
    <div className="space-y-5">
      <h1 className="text-xl font-bold text-white-100">Content Library</h1>

      {tabBar}

      {/* Filters row */}
      <div className="space-y-3">
        <div className="flex items-center gap-3">
          <div className="relative flex-1 max-w-sm">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-white-30" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search content..."
              className="w-full pl-9 pr-3 py-2 rounded-lg bg-white-5 border border-white-10 text-white-100 text-sm focus:outline-none focus:border-accent-green-110"
            />
          </div>

          {/* View toggle */}
          <div className="flex rounded-lg bg-white-5 border border-white-10 p-0.5 ml-auto">
            <button
              onClick={() => setViewMode('list')}
              className={cn(
                'p-1.5 rounded-md transition-colors',
                viewMode === 'list' ? 'bg-white-10 text-white-100' : 'text-white-40 hover:text-white-60'
              )}
              title="List view"
            >
              <List className="w-4 h-4" />
            </button>
            <button
              onClick={() => setViewMode('grid')}
              className={cn(
                'p-1.5 rounded-md transition-colors',
                viewMode === 'grid' ? 'bg-white-10 text-white-100' : 'text-white-40 hover:text-white-60'
              )}
              title="Grid view"
            >
              <LayoutGrid className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Channel + source filters */}
        <div className="flex items-center gap-4 flex-wrap">
          <div className="flex items-center gap-1.5 flex-wrap">
            {CHANNEL_FILTERS.map((f) => (
              <button
                key={f.value}
                onClick={() => setChannelFilter(f.value)}
                className={cn(
                  'px-2.5 py-1 rounded text-xs font-medium transition-colors',
                  channelFilter === f.value
                    ? 'bg-white-20 text-white-100'
                    : 'text-white-40 hover:text-white-60'
                )}
              >
                {f.label}
              </button>
            ))}
          </div>

          <div className="w-px h-4 bg-white-10" />

          <div className="flex items-center gap-1.5 flex-wrap">
            {SOURCE_FILTERS.map((f) => {
              const count = sourceCounts[f.value] ?? 0;
              return (
                <button
                  key={f.value}
                  onClick={() => setSourceFilter(f.value)}
                  className={cn(
                    'flex items-center gap-1 px-2.5 py-1 rounded text-xs font-medium transition-colors',
                    sourceFilter === f.value
                      ? 'bg-white-20 text-white-100'
                      : 'text-white-40 hover:text-white-60'
                  )}
                >
                  {f.icon}
                  {f.label}
                  {f.value !== 'all' && count > 0 && (
                    <span className="text-white-30 ml-0.5">({count})</span>
                  )}
                </button>
              );
            })}
          </div>
        </div>
      </div>

      {/* Results count */}
      {drafts && allDrafts && drafts.length !== allDrafts.length && (
        <p className="text-xs text-white-30">
          Showing {drafts.length} of {allDrafts.length}
        </p>
      )}

      {/* Draft list */}
      {isLoading && (
        <div className="flex items-center gap-2 py-6">
          <LoadingSpinner size="sm" />
          <span className="text-white-40 text-sm">Loading content...</span>
        </div>
      )}

      {error && <StatusBanner error={(error as Error).message} />}

      {drafts && drafts.length === 0 && (
        <div className="card p-8 text-center">
          <Inbox className="w-8 h-8 text-white-40 mx-auto mb-2" />
          <p className="text-sm text-white-60">
            {searchQuery ? 'No content matches your search.' : 'No content in this category.'}
          </p>
        </div>
      )}

      {drafts && drafts.length > 0 && (
        <div className={viewMode === 'grid'
          ? 'grid grid-cols-1 md:grid-cols-2 gap-4'
          : 'space-y-4'
        }>
          {drafts.map((draft) => (
            <DraftQueueCard key={draft.id} draft={draft} />
          ))}
        </div>
      )}
    </div>
  );
}
